### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by vladikoff** [sessamekesh/wasm-3d-animation-demo#1]
Hey @sessamekesh , seems like the site at http://aws-website-webassemblyskeletalanimation-ffaza.s3-website-us-east-1.amazonaws.com/ is down 😿

**Comment by sessamekesh** [comment]
Oh no! That's not good...

Are you getting any special kind of error? 404, 503, etc.? It pulls from a couple of very big resources that have a tendency to fail on mobile - I really ought to put them into a more compressed data format...

**Comment by vladikoff** [comment]
@sessamekesh does it load for you? 

I'm getting 

> aws-website-webassemblyskeletalanimation-ffaza.s3-website-us-east-1.amazonaws.com took too long to respond.

**Comment by vladikoff** [comment]
@sessamekesh gah my fault, FORCED HTTPS.

Sorry to waste your time, Excellent demo by the way 👍

**Comment by sessamekesh** [comment]
@vladikoff Well thanks for the heads up anyways, I'm sure you're not the only one with FORCED HTTPS. I'll look into getting an HTTPS endpoint up... Right now it's just a static S3 site, I haven't bothered to get a key for it or anything.

No problem, I happened to be at my computer anyways. I'm glad you like the demo!
